# Q1: Addition of Angular Momentum

### In this question we will use numpy to create proper matrix representing the angular momentum operators in proper spaces and deduce Clebch-Gordan coefficients from them by diagonalizing $L_{tot}^2$

In [1]:
import numpy as np
from numpy import linalg as LA

### a) by using Algebraic relation between rotation matrices, write down the matrix representation of $L^2$, $L_-$, $L_+$, $L_x$, $L_y$, $L_z$ in the basis of $|l,m\rangle$ where $l=2$ and $l=\frac{3}{2}$. 
Theses are the algebraic relations between rotation matrices:
$$
\begin{align}
L_+|l,m\rangle &= \hbar\sqrt{l(l+1)-m(m+1)}|l,m+1\rangle \\
L_-|l,m\rangle &= \hbar\sqrt{l(l+1)-m(m-1)}|l,m-1\rangle \\
L_z|l,m\rangle &= \hbar m|l,m\rangle \\
L^2|l,m\rangle &= \hbar^2l(l+1)|l,m\rangle
\end{align}
$$
$$
\begin{align}
L_x &= \frac{1}{2}(L_+ + L_-) \\
L_y &= \frac{1}{2i}(L_+ - L_-) \\
L_z &= L_z
\end{align}
$$
In the next code block we will define a function which outputs the matrix representation of angular momentum operators with given $l$. thorughout this question we will use $\hbar=1$.

In [40]:
def AngularMomentum(l):
    dim = int(2*l+1)
    Jz = np.zeros((dim,dim))
    J2 = np.zeros((dim,dim))
    Jp = np.zeros((dim,dim))
    Jn = np.zeros((dim,dim))
    for i in range(dim):
        Jz[i,i] = l-i
        J2[i,i] = l*(l+1)
        if i < dim-1:
            Jp[i,i+1] = np.sqrt(l*(l+1)-(l-i-1)*(l-i))
            Jn[i+1,i] = np.sqrt(l*(l+1)-(l-i-1)*(l-i))
    Jx = 0.5*(Jp+Jn)
    Jy = -0.5j*(Jp-Jn)
    return np.array([Jx,Jy,Jz,Jp,Jn,J2,np.eye(dim)])

This will create the matrices needed for computation of Clebch-Gordan coefficients. Now we put $l=2$ and $l=\frac{3}{2}$ in the function and get the matrices.

In [69]:
AngularMomentums1 = AngularMomentum(1/2)
AngularMomentums2 = AngularMomentum(1/2)

### b) By using tensor product derive the matrix representation of $L^2$, $L_-$, $L_+$, $L_x$, $L_y$, $L_z$ in the basis of $|l_1,m_1\rangle\otimes|l_2,m_2\rangle$ where $l_1=2$, $l_2=\frac{3}{2}$ and $m_1=-l_1,-l_1+1,...,l_1$ and $m_2=-l_2,-l_2+1,...,l_2$.

Here we calculate each operator By noting that:
$$
L_a = L_a^{(1)}\otimes I^{(2)} + I^{(1)}\otimes L_a^{(2)}
$$

In [70]:

LxTotal = np.kron(AngularMomentums1[0],AngularMomentums2[6])+np.kron(AngularMomentums1[6],AngularMomentums2[0])
LyTotal = np.kron(AngularMomentums1[1],AngularMomentums2[6])+np.kron(AngularMomentums1[6],AngularMomentums2[1])
LzTotal = np.kron(AngularMomentums1[2],AngularMomentums2[6])+np.kron(AngularMomentums1[6],AngularMomentums2[2])
LpTotal = np.kron(AngularMomentums1[3],AngularMomentums2[6])+np.kron(AngularMomentums1[6],AngularMomentums2[3])
LnTotal = np.kron(AngularMomentums1[4],AngularMomentums2[6])+np.kron(AngularMomentums1[6],AngularMomentums2[4])

To calculate $L_{tot}^2$ we use the following formula:
$$
L_{tot}^2 = L_x^2+L_y^2+L_z^2
$$

In [71]:
LtwoTotal = LxTotal@LxTotal + LyTotal@LyTotal + LzTotal@LzTotal
LtwoTotal = LtwoTotal.astype(np.float64) # to avoid complex numbers
LtwoTotal

C:\Users\fox\AppData\Local\Temp\ipykernel_9404\3427952435.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  LtwoTotal = LtwoTotal.astype(np.float64) # to avoid complex numbers


array([[2., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 2.]])

### c) Diagonalize $L_{tot}^2$ and find the Clebch-Gordan coefficients for $l_1=2$, $l_2=\frac{3}{2}$ and $m_1=-l_1,-l_1+1,...,l_1$ and $m_2=-l_2,-l_2+1,...,l_2$.

In order to do this we use linalg.eig function to find the eigenvalues and eigenvectors of $L_{tot}^2$ and then we use the eigenvectors to find the Clebch-Gordan coefficients.
The Clebch-Gordan coefficients are the coefficients of the eigenvectors in the basis of $|l_1,m_1\rangle\otimes|l_2,m_2\rangle$. i.e. if we have an eigenvector $|l_1,l_2,m_1+m_2,l\rangle$ of $L_{tot}^2$ then the Clebch-Gordan coefficients are the coefficients of $|l_1,l_2,m_1+m_2,l\rangle$ in the basis of $|l_1,m_1\rangle\otimes|l_2,m_2\rangle$.

In [72]:
Eigenvalues, Eigenvectors = LA.eig(LtwoTotal)


In [96]:
Eigenvalues

array([2., 0., 2., 2.])

In [97]:
Eigenvectors

array([[ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

## Clebch-Gordan Coefficients:
$$
|l_1,l_2,m_1+m_2,l\rangle = \sum_{m_1,m_2}C_{l_1,l_2,m_1,m_2}^{l,m_1+m_2}|l_1,m_1\rangle\otimes|l_2,m_2\rangle
$$
where $C_{l_1,l_2,m_1,m_2}^{l,m_1+m_2}$ are the Clebch-Gordan coefficients.
$$
C_{l_1,l_2,m_1,m_2}^{l,m_1+m_2} = \langle l_1,l_2,m_1,m_2|l_1,l_2,m_1+m_2,l\rangle
$$
we will calculate the Clebch-Gordan coefficients by using the eigenvectors of $L_{tot}^2$ as follows:

In [95]:
def CG(m1,m2,l): # Clebsch-Gordan coefficients (m1,m2,l)
    l1 = float(AngularMomentums1[2,0,0].real)
    l2 = float(AngularMomentums2[2,0,0].real)
    rangeL = int(l1+l2-abs(l1-l2)+1)
    Coefficients = np.zeros((int(2*l1+1),int(2*l2+1),rangeL))
    States = 
    for i in range(rangeL):
        indexes = np.argwhere(Eigenvalues==(i*(i+1)))


    indexes = np.argwhere(Eigenvalues==(i*(i+1)))
    productState = np.kron()
    print(indexes)

[[1]]
[[0]
 [2]
 [3]]


In [ ]:
def ClebchGordan(l1,l2,m1,m2,l):
    dim1 = int(2*l1+1)
    dim2 = int(2*l2+1)
    dim = int(2*l+1)
    CG = np.zeros((dim1,dim2,dim))
    for i in range(dim1):
        for j in range(dim2):
            for k in range(dim):
                if m1+l1-i == m2+l2-j and m1+l1-i == l-k and m1+l1-i >= 0 and m2+l2-j >= 0 and l-k >= 0:
                    CG[i,j,k] = np.sqrt((2*l1+1)*(2*l2+1)*(2*l+1)/(4*np.pi))*LA.multi_dot([[AngularMomentum(l1)[6][i,i],AngularMomentum(l2)[6][j,j],AngularMomentum(l)[6][k,k]],[AngularMomentum(l1)[6],AngularMomentum(l2)[6],AngularMomentum(l)[6]]])
    return CG

In [64]:
Eigenvalues

array([2., 0., 2., 2.])

In [65]:
Eigenvectors

array([[ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])